name: Scribe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_quill: 10.5.14
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.0
  get: ^4.6.6
  http: ^1.2.1
  video_player: ^2.9.1
  change_app_package_name: ^1.3.0
  cloud_firestore: ^5.4.2
  intl: ^0.19.0
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

fonts:
    - family: RubicMonicOne
      fonts:
        - asset: assets/fonts/assets/fonts/RubikMonoOne-Regular.ttf
          style: 