name: writing_feed_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_quill: ^10.5.18
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.0
  get: ^4.6.6
  http: ^1.2.1
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google.png
    - assets/facebook.png
    - assets/background.jpg
    - assets/background2.jpg
