// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAUTUZg0KWsrLBZIddCEKQrJmIaCj7csQ',
    appId: '1:190630699003:web:a3a9e43da339ec1307f55e',
    messagingSenderId: '190630699003',
    projectId: 'congressional-app-challe-463c2',
    authDomain: 'congressional-app-challe-463c2.firebaseapp.com',
    storageBucket: 'congressional-app-challe-463c2.appspot.com',
    measurementId: 'G-80WJELMBR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS4hsC84O6dRaKxGcWMhsmi3Gy9FUHbZQ',
    appId: '1:190630699003:android:3f0c2a87a584808607f55e',
    messagingSenderId: '190630699003',
    projectId: 'congressional-app-challe-463c2',
    storageBucket: 'congressional-app-challe-463c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPZ7TD3W7LHvruHSBBnsy0FOWp_yOob4Y',
    appId: '1:190630699003:ios:f1edf25cee66faa207f55e',
    messagingSenderId: '190630699003',
    projectId: 'congressional-app-challe-463c2',
    storageBucket: 'congressional-app-challe-463c2.appspot.com',
    iosBundleId: 'com.example.writingFeedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPZ7TD3W7LHvruHSBBnsy0FOWp_yOob4Y',
    appId: '1:190630699003:ios:f1edf25cee66faa207f55e',
    messagingSenderId: '190630699003',
    projectId: 'congressional-app-challe-463c2',
    storageBucket: 'congressional-app-challe-463c2.appspot.com',
    iosBundleId: 'com.example.writingFeedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAUTUZg0KWsrLBZIddCEKQrJmIaCj7csQ',
    appId: '1:190630699003:web:f70c4a88fe5fa55b07f55e',
    messagingSenderId: '190630699003',
    projectId: 'congressional-app-challe-463c2',
    authDomain: 'congressional-app-challe-463c2.firebaseapp.com',
    storageBucket: 'congressional-app-challe-463c2.appspot.com',
    measurementId: 'G-EFSF61PBQ0',
  );
}
